//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet23_Station_météo_WPF.ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projet23_Station_météo_WPF.ressources.Configs", typeof(Configs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #FF17B917;#FF15960E;#FFB9B217;#FF96900E;#FFB92D17;#FF96210E.
        /// </summary>
        internal static string colorSeuils {
            get {
                return ResourceManager.GetString("colorSeuils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30.
        /// </summary>
        internal static string refreshTimer {
            get {
                return ResourceManager.GetString("refreshTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string saveIdentifiant {
            get {
                return ResourceManager.GetString("saveIdentifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string saveMdp {
            get {
                return ResourceManager.GetString("saveMdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stationmeteo.loritz.fr.
        /// </summary>
        internal static string serverIp {
            get {
                return ResourceManager.GetString("serverIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30;30;30;30.
        /// </summary>
        internal static string seuilLvl1 {
            get {
                return ResourceManager.GetString("seuilLvl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 60;60;60;60.
        /// </summary>
        internal static string seuilLvl2 {
            get {
                return ResourceManager.GetString("seuilLvl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à °.
        /// </summary>
        internal static string unitDvent {
            get {
                return ResourceManager.GetString("unitDvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à %.
        /// </summary>
        internal static string unitHygro {
            get {
                return ResourceManager.GetString("unitHygro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mm.
        /// </summary>
        internal static string unitPluv {
            get {
                return ResourceManager.GetString("unitPluv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hPa.
        /// </summary>
        internal static string unitPresAtmo {
            get {
                return ResourceManager.GetString("unitPresAtmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W/m².
        /// </summary>
        internal static string unitRaySol {
            get {
                return ResourceManager.GetString("unitRaySol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à °C.
        /// </summary>
        internal static string unitTemp {
            get {
                return ResourceManager.GetString("unitTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Km/h.
        /// </summary>
        internal static string unitVvent {
            get {
                return ResourceManager.GetString("unitVvent", resourceCulture);
            }
        }
    }
}
